version: '3'
services:
  app:
      build: .
      container_name: app
      env_file:
        - .env
      ports:
        - "5000:5000"
      depends_on:
        - db
  db:
    image: mysql/mysql-server:5.7
    container_name: db
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql/

volumes:
  db_data:
    driver: local